#!/usr/bin/env python3
import math
import re
import sys
import os
from os import path
from os import system
import signal
import subprocess
from subprocess import PIPE, STDOUT
from glob import glob

# run `play` with cpu limitig
args = sys.argv[1:]
if len(args) == 6:
    nodes = args[0]
    elo_guess = args[1]
    elo_delta = args[2]
    min_opps = args[3]
    tc = args[4]
    cpu_percent = int(args[5])
    ss = tc.split('+')
    mins = float(ss[0]) * 100 / cpu_percent
    secs = float(ss[1]) * 100 / cpu_percent
    scaled_tc = "%s+%s" % (mins, secs)
    print('time contol scaled from %s to %s' % (tc, scaled_tc))
    cmd = (
        (
            'sudo systemd-run --scope --uid=1000 -p CPUQuota=%d%% -E PATH=$PATH ' +
            './play %s %s %s %s %s'
        ) % (
            cpu_percent,
            nodes, elo_guess, elo_delta, min_opps, scaled_tc
        )
    )
    print(cmd)
    exit(system(cmd))
else:
    print('usage: slowplay nodes elo-guess guess-delta min-opponents time-control cpu-limit-percents')
    exit(1)
