#!/usr/bin/env python3

usage = 'clone git-repo [branch] [elo_elo-accuracy]'

import math
import re
import sys
import os
from os import path
from os import system
import signal
import subprocess
from subprocess import PIPE, STDOUT
from glob import glob

args = sys.argv[1:]

if len(args) == 0:
    print(usage)
    exit(1)

repo = args[0]
name = repo.split('/')[-1].removesuffix('.git')
branch = ''
elo_acc = ''

if len(args) == 3:
    branch = args[1]
    elo_acc = args[2]
elif len(args) == 2:
    if '_' in args[1] and all([arg.isnumeric() for arg in args[1].split('_')]):
        elo_acc = args[1]
    else:
        branch = args[1]

if branch:
    cmd_args = '--branch %s' % branch
else:
    cmd_args = ''

if elo_acc:
    dest = elo_acc + '_' + name
else:
    dest = name

if branch:
    dest = dest + '-' + branch

cmd = 'git clone --depth=1 --separate-git-dir=$(mktemp -u) %s %s %s && rm %s/.git' % (cmd_args, repo, dest, dest)
print(cmd)
system(cmd)
#os.chdir(dest)
